### ISSUE TITLE
其他版本的预训练bert也可以用吗

### ISSUE THREAD

**Issue by Williamlizl** [YaoXinZhi/Convert-Bert-TF-checkpoint-to-Pytorch#1]

**Comment by YaoXinZhi** [comment]
可以的 只要是和Google官方模型结构相同的Bert的TensorFlow的CheckPoint都可以用 我自己用这个代码把BioBert (一个在生物医学语料库中预训练的TF-Bert-checkpoint)转换为Pytorch版本 经测试可用

**Comment by Williamlizl** [comment]
> 可以的 只要是和Google官方模型结构相同的Bert的TensorFlow的CheckPoint都可以用 我自己用这个代码把BioBert (一个在生物医学语料库中预训练的TF-Bert-checkpoint)转换为Pytorch版本 经测试可用

谢谢，我也是转换一个医学的，https://github.com/alibaba-research/ChineseBLUE，试试可不可以用
