### ISSUE TITLE
保存后不是文件夹，而是一个文件格式，怎么解决呢？

### ISSUE THREAD

**Issue by Yu-Yuqing** [YaoXinZhi/Convert-Bert-TF-checkpoint-to-Pytorch#2]
如题，感谢
![image](https://user-images.githubusercontent.com/77087768/130047623-999d3825-e055-4ee1-81ec-8f1a05a871a8.png)

**Comment by YaoXinZhi** [comment]
你可以查看下我README里提供的简书链接或者分段运行源码检查是否运行正确，参数没问题的话代码应该是ok的

**Comment by Yu-Yuqing** [comment]
解决啦，就是个文件，命名错误，以为生成的文件夹，谢谢！



---Original---
From: ***@***.***&gt;
Sent at: 2021年8月19日(Thu) Evening8:12
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [YaoXinZhi/Convert-Bert-TF-checkpoint-to-Pytorch] 保存后不是文件夹，而是一个文件格式，怎么解决呢？ (#2)




 
你可以查看下我README里提供的简书链接或者分段运行源码检查是否运行正确，参数没问题的话代码应该是ok的
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by YaoXinZhi** [comment]
嗯呐客气了。
